openapi: 3.0.3
info:
  title: Explay - API 0.3.0
  version: 0.3.0
  description: |-
    Especificações para integração com a API da plataforma Explay
  contact:
    name: Explay
    url: https://api.whatsapp.com/send?phone=5516997744203
servers:
  - url: https://api-usinalins.explay.app.br/external/v1
paths:
  /custom-fields:
    get:
      tags:
        - Custom field
      summary: Lista campos personalizados
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example:
                current_page: 1
                data:
                  - id_custom_field: 4
                    name_custom_field: Curso obrigatório
                    description: Define se o curso é obrigatório
                    help: ''
                    required: true
                    created_at: 2020-10-10 10:20:15
                    updated_at: 2020-10-11 11:38:12
                    integration_key: ''
                    entity:
                      id_entity: 2
                      name_entity: Curso
                    options:
                      - id_custom_field_option: 7
                        id_custom_field: 4
                        created_at: 2020-10-10 10:20:15
                        updated_at: 2020-10-11 11:38:12
                      - id_custom_field_option: 8
                        id_custom_field: 4
                        created_at: 2020-10-10 10:20:15
                        updated_at: 2020-10-11 11:38:12
                  - ...
                first_page_url: "https://api-usinalins.explay.app.br/external/v1/custom-fields?page=1"
                from: 1
                last_page: 2,
                last_page_url: "https://api-usinalins.explay.app.br/external/v1/custom-fields?page=2"
                next_page_url: "https://api-usinalins.explay.app.br/external/v1/custom-fields?page=2"
                path: "https://api-usinalins.explay.app.br/external/v1/custom-fields"
                per_page: 15
                prev_page_url: null
                to: 15
                total: 18
        '401':
          description: Unauthorized
  /users:
    get:
      tags:
        - User
      summary: Lista usuários
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example:
                current_page: 1
                data:
                  - id_user: 1
                    name_user: Administrador
                    email: admin@elydi.com
                    updated_at: '2023-11-09 23:54:13'
                    created_at: '2023-11-09 23:54:13'
                  - ...
                first_page_url: https://api-usinalins.explay.app.br/external/v1/users?page=1
                from: 1
                last_page: 1
                last_page_url: https://api-usinalins.explay.app.br/external/v1/users?page=1
                next_page_url: null
                path: https://api-usinalins.explay.app.br/external/v1/users
                per_page: 15
                prev_page_url: null
                to: 15
                total: 15
        '401':
          description: Unauthorized
    post:
      tags:
        - User
      summary: Cadatra um novo usuário
      requestBody:
        content:
          application/json:
            example:
              name_user: Ricardo da Silva
              email: ricardo@example.com
              custom_fields:
                cpf: 000.000.000-00
                telefone: (00) 00000-0000
      responses:
        '201':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithCustomField'
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable
          content:
            application/json:
              example:
                validation_errors:
                  name_user:
                    - Este campo é obrigatório
                  email:
                    - Este campo é obrigatório
  /users/{id}:
    get:
      tags:
        - User
      summary: Visualiza usuário por ID
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithCustomField'
        '401':
          description: Unauthorized
    put:
      tags:
        - User
      summary: Atualiza um usuário.
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            example:
              name_user: Ricardo Almeida
              email: ricardo-almeida@example.com
              custom_fields:
                cpf: 111.111.111-11
                telefone: (11) 11111-1111
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithCustomField'
        '401':
          description: Unauthorized

components:
  schemas:
    CustomField:
      type: object
      properties:
        id_custom_field:
          type: integer
          format: int64
          example: 10
        name_custom_field:
          type: string
        description:
          type: string
        help:
          type: string
        integration_key:
          type: string
          example: codigo_interno
          description: O valor do campo deve ser único.
        required:
          type: boolean
          example: true
        created_at:
          type: string
          example: '2020-10-10 10:20:15'
        updated_at:
          type: string
          example: '2020-10-11 11:38:12'
    CustomFieldOption:
      type: object
      properties:
        id_custom_field_option:
          type: integer
          format: int64
          example: 10
        name_custom_field_option:
          type: string
        description:
          type: string
        order:
          type: integer
        integration_key:
          type: string
          example: codigo_interno
          description: O valor do campo deve ser único.
        id_custom_field:
          type: integer
          format: int64
          example: 10
        created_at:
          type: string
          example: '2020-10-10 10:20:15'
        updated_at:
          type: string
          example: '2020-10-11 11:38:12'
    CustomFieldAnswer:
      type: object
      properties:
        id_custom_field_answer:
          type: integer
          format: int64
          example: 10
        short_text_answer:
          type: string
        long_text_answer:
          type: string
        numeric_answer:
          type: integer
        id_custom_field:
          type: integer
          format: int64
          example: 10
        created_at:
          type: string
          example: '2020-10-10 10:20:15'
        updated_at:
          type: string
          example: '2020-10-11 11:38:12'
    CustomFieldWithOptions:
      type: object
      properties:
        id_custom_field:
          type: integer
          format: int64
          example: 10
        name_custom_field:
          type: string
        description:
          type: string
        help:
          type: string
        integration_key:
          type: string
          example: codigo_interno
          description: O valor do campo deve ser único.
        required:
          type: boolean
          example: true
        created_at:
          type: string
          example: '2020-10-10 10:20:15'
        updated_at:
          type: string
          example: '2020-10-11 11:38:12'
        options:
          type: array
          items:
            $ref: '#/components/schemas/CustomFieldOption'
    CustomFieldWithAnswers:
      type: object
      properties:
        id_custom_field:
          type: integer
          format: int64
          example: 10
        name_custom_field:
          type: string
        description:
          type: string
        help:
          type: string
        integration_key:
          type: string
          example: codigo_interno
          description: O valor do campo deve ser único.
        required:
          type: boolean
          example: true
        created_at:
          type: string
          example: '2020-10-10 10:20:15'
        updated_at:
          type: string
          example: '2020-10-11 11:38:12'
        answers:
          type: array
          items:
            $ref: '#/components/schemas/CustomFieldAnswer'
    Entity:
      type: object
      properties:
        id_entity:
          type: integer
          format: int64
          example: 10
        name_entity:
          type: string
          example: User
    User:
      type: object
      required:
        - name_user
        - email
      properties:
        id_user:
          type: integer
          format: int64
          example: 10
        name_user:
          type: string
          example: João Pinheiro
        email:
          type: string
          example: email@example.com
        created_at:
          type: string
          example: '2020-10-10 10:20:15'
        updated_at:
          type: string
          example: '2020-10-11 11:38:12'
    UserWithCustomField:
      type: object
      required:
        - name_user
        - email
      properties:
        id_user:
          type: integer
          format: int64
          example: 10
        name_user:
          type: string
          example: João Pinheiro
        email:
          type: string
          example: email@example.com
        ind_admin:
          type: boolean
          example: true
          description: Define se o usuário é administrador do sistema.
          default: false
        created_at:
          type: string
          example: '2020-10-10 10:20:15'
        updated_at:
          type: string
          example: '2020-10-11 11:38:12'
        custom_fields:
          type: array
          items:
            $ref: '#/components/schemas/CustomFieldWithOptions'
  parameters:
    id:
      name: id
      in: path
      description: id do usuário
      required: true
      schema:
        type: string
